<Project Sdk="Microsoft.NET.Sdk">

	
	
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Include="src\Features\KillCooldown.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ds5678.Modding.Unity.KeyboardUtilities" Version="2.0.0" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppEpic.OnlineServices.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Addressables.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Common.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Realtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Runtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Scripts.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppFusion.Sockets.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppGilgaMesh.Runtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppNanoSockets.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppOculus.Platform.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppOculus.VR.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppPhoton3Unity3D.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppPhotonRealtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.API.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.Fusion.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Airlock.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.AutoPerf.Data.Airlock.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.AutoPerf.Data.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.AutoPerf.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Core.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.EosSDK2.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.FusionSimulator.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.GlobalEvents.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.LightTween.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.LightUI.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.OVRMetricsToolkitExtension.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Airlock3D.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Oculus.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.QADebug.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.SimulatedXR.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Steam.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.PlayerLoops.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.Oculus.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.Steam.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.SoundCore.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.VAT.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSG.Vignettitor.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSteamVR.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSteamVR_Actions.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSystem.Drawing.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppSystem.Net.Http.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppToxMod.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2CppValve.Newtonsoft.Json.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2Cppwebsocket-sharp.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Il2Cpp__Generated.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.InputSystem.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.InputSystem.ForUI.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.InputSystem.RebindingUI.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Localization.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.MemoryProfiler.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.KdTree.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.Poly2Tri.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Profiling.Core.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.RenderPipeline.Universal.ShaderLibrary.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Core.Runtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Universal.Runtime.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Analytics.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Configuration.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Device.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Environments.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Environments.Internal.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Internal.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Registration.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Scheduler.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Telemetry.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.Services.Core.Threading.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.CoreUtils.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.Interaction.Toolkit.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.Management.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.MockHMD.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.Oculus.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\Unity.XR.OpenVR.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\UnityEngine.ContentLoadModule.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\UnityEngine.PropertiesModule.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\UnityEngine.SpatialTracking.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\UnityEngine.UnityAnalyticsCommonModule.dll">
		  <Private>false</Private>
		</Reference>
		<Reference Include="D:\SteamLibrary\steamapps\common\Among Us VR\MelonLoader\Il2CppAssemblies\UnityEngine.XR.LegacyInputHelpers.dll">
		  <Private>false</Private>
		</Reference>
	</ItemGroup>
	
</Project>
